"""create project and chat tables

Revision ID: 5836d2ed7427
Revises: 1cb012775886
Create Date: 2026-06-15 12:57:18.681408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5836d2ed7427'
down_revision: Union[str, Sequence[str], None] = '1cb012775886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('health_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('budget', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('budget_used', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_end_date', sa.Date(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_used', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_recommendations',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_resources',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('allocation_percent', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_risks',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprint_data',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sprint_number', sa.Integer(), nullable=False),
    sa.Column('velocity', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('assessment_categories', 'framework_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('assessment_categories_framework_id_fkey'), 'assessment_categories', type_='foreignkey')
    op.create_foreign_key('fk_assessment_categories_framework_id', 'assessment_categories', 'maturity_frameworks', ['framework_id'], ['id'], ondelete='CASCADE')
    op.alter_column('assessment_questions', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('assessment_questions_category_id_fkey'), 'assessment_questions', type_='foreignkey')
    op.create_foreign_key('fk_assessment_questions_category_id', 'assessment_questions', 'assessment_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('assessment_responses', 'assessment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('assessment_responses', 'question_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('assessment_responses_assessment_id_fkey'), 'assessment_responses', type_='foreignkey')
    op.drop_constraint(op.f('assessment_responses_question_id_fkey'), 'assessment_responses', type_='foreignkey')
    op.create_foreign_key('fk_assessment_responses_question_id', 'assessment_responses', 'assessment_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_assessment_responses_assessment_id', 'assessment_responses', 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('assessments', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('assessments', 'framework_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('assessments_framework_id_fkey'), 'assessments', type_='foreignkey')
    op.drop_constraint(op.f('assessments_org_id_fkey'), 'assessments', type_='foreignkey')
    op.create_foreign_key('fk_assessments_org_id', 'assessments', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_assessments_framework_id', 'assessments', 'maturity_frameworks', ['framework_id'], ['id'], ondelete='CASCADE')
    op.alter_column('maturity_scores', 'assessment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('maturity_scores', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('maturity_scores', 'score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('maturity_scores', 'level',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(op.f('maturity_scores_assessment_id_fkey'), 'maturity_scores', type_='foreignkey')
    op.drop_constraint(op.f('maturity_scores_category_id_fkey'), 'maturity_scores', type_='foreignkey')
    op.create_foreign_key('fk_maturity_scores_category_id', 'maturity_scores', 'assessment_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_maturity_scores_assessment_id', 'maturity_scores', 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_maturity_scores_assessment_id', 'maturity_scores', type_='foreignkey')
    op.drop_constraint('fk_maturity_scores_category_id', 'maturity_scores', type_='foreignkey')
    op.create_foreign_key(op.f('maturity_scores_category_id_fkey'), 'maturity_scores', 'assessment_categories', ['category_id'], ['id'])
    op.create_foreign_key(op.f('maturity_scores_assessment_id_fkey'), 'maturity_scores', 'assessments', ['assessment_id'], ['id'])
    op.alter_column('maturity_scores', 'level',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('maturity_scores', 'score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('maturity_scores', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('maturity_scores', 'assessment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('fk_assessments_framework_id', 'assessments', type_='foreignkey')
    op.drop_constraint('fk_assessments_org_id', 'assessments', type_='foreignkey')
    op.create_foreign_key(op.f('assessments_org_id_fkey'), 'assessments', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(op.f('assessments_framework_id_fkey'), 'assessments', 'maturity_frameworks', ['framework_id'], ['id'])
    op.alter_column('assessments', 'framework_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('assessments', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('fk_assessment_responses_assessment_id', 'assessment_responses', type_='foreignkey')
    op.drop_constraint('fk_assessment_responses_question_id', 'assessment_responses', type_='foreignkey')
    op.create_foreign_key(op.f('assessment_responses_question_id_fkey'), 'assessment_responses', 'assessment_questions', ['question_id'], ['id'])
    op.create_foreign_key(op.f('assessment_responses_assessment_id_fkey'), 'assessment_responses', 'assessments', ['assessment_id'], ['id'])
    op.alter_column('assessment_responses', 'question_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('assessment_responses', 'assessment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('fk_assessment_questions_category_id', 'assessment_questions', type_='foreignkey')
    op.create_foreign_key(op.f('assessment_questions_category_id_fkey'), 'assessment_questions', 'assessment_categories', ['category_id'], ['id'])
    op.alter_column('assessment_questions', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('fk_assessment_categories_framework_id', 'assessment_categories', type_='foreignkey')
    op.create_foreign_key(op.f('assessment_categories_framework_id_fkey'), 'assessment_categories', 'maturity_frameworks', ['framework_id'], ['id'])
    op.alter_column('assessment_categories', 'framework_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('sprint_data')
    op.drop_table('project_risks')
    op.drop_table('project_resources')
    op.drop_table('ai_recommendations')
    op.drop_table('ai_messages')
    op.drop_table('projects')
    op.drop_table('conversations')
    # ### end Alembic commands ###
